### ISSUE TITLE
Zenn本での誤植？

### ISSUE THREAD

**Issue by masakinihirota** [typebase-inc/trpc-introduction-support#1]
https://zenn.dev/typebase/books/trpc-introduction/viewer/6-trpc-webapp

>である SKIP_ENV_VALIDATION を有効にした上でこれらのコマンドを叩くと良いでしょう。

>SKIP_ENV_VALIDATION=1 npm run lint

>続いて、NextAuth.js で使うプロバイダーの設定を追加します。NextAuth.js の認証のエンド

この`SKIP_ENV_VALIDATION=1 npm run lint`は誤植ではないでしょうか？

**Comment by y-temp4** [comment]
@masakinihirota ご指摘いただき、ありがとうございます！

こちらですが、どのような記述が本来正しいと思われていますか？ご確認いただけますと幸いです！

**Comment by masakinihirota** [comment]
環境 Windows10
VSCode
PowerShell

本文の通りコマンドを入力すると画像のようになりました。
PowerShellでは受け付けてくれませんでした。

![コマンドでエラーが出る](https://github.com/typebase-inc/trpc-introduction-support/assets/7696510/2b162c54-878d-4e60-a888-54d9bd26ce2a)

**Comment by y-temp4** [comment]
エラー画面をご共有いただき、ありがとうございます！
こちらですが、[公式サイト](https://create.t3.gg/en/deployment/docker) を参考に作成したものなのですが、おそらくmacOSやLinux環境のみで動作するようです。
PowerShellの場合は以下をお試しいただくか、`cross-env`などのパッケージを使って実行するのが良さそうです。

```shell
$env:SKIP_ENV_VALIDATION="1"; npm run lint
```

`cross-env`での実行例：

```shell
 npx cross-env SKIP_ENV_VALIDATION=1 npm run lint
```

参考：[dotenvとcross-envで環境変数を設定して開発環境の処理を切り替える ｜ Tips Note by TAM](https://www.tam-tam.co.jp/tipsnote/program/post17589.html)

**Comment by masakinihirota** [comment]
わかりました、ありがとうございます。
